---
title: "Data Import"
output: github_document
---


# Section 1

Here's a **code chunk** that samples from 
a _normal distribution_:

```{r setup, echo = FALSE, message = FALSE}
library(dplyr)
library(tidyverse)
```
# Shows how to manipulate data

```{r}
litters_df <- read_csv("data_import_examples/data_import_examples/FAS_litters.csv",
                       na = c("NA", ".", ""))

litters_df <- janitor::clean_names(litters_df)

pups_df <- read_csv("data_import_examples/data_import_examples/FAS_pups.csv",
                    na = c("NA", ".", ""))
pups_df <- janitor::clean_names(pups_df)

```

## Select

```{r}
#selecting columns

select(litters_df, group, litter_number, gd0_weight, gd0_weight, pups_born_alive)

```


```{r}
#selecting range of columns

select(litters_df, group:gd_of_birth)

```

```{r}
# removes a column

select(litters_df, -pups_survive)
```

```{r}
# rename variable as part of the process
select(litters_df, GROUP = group, LiTtEr_NuMber = litter_number)

# or use rename function
rename(litters_df, GROUP = group)

```

```{r}
# Moving Columns, this code will move the 3 specified columns to the right of
# everything else
select(litters_df, litter_number, pups_survive, everything())

# similar function with relocate
relocate(litters_df, litter_number, pups_survive)

```

```{r}
# Learning Check

select(pups_df, litter_number, sex, pd_ears)
```




## Filter

```{r}
filter(litters_df, gd_of_birth == 20)
filter(litters_df, gd_of_birth == 19)
```

```{r}
filter(litters_f, pups_born_alive != 9)
```

```{r}
filter(litters_df, group == "Low8")
filter(litters_df, group %in% c("Low7", "Low8"))

```

```{r}
filter(litters_df, group %in% c("Low7", "Low8"), pups_born_alive == 8)
```

```{r}

```

